//! Runner for the normative collections conformance corpus
//! `hara-specs-registry/01-lang/020-data-structures/draft/conformance/collections.edn`
//! (generated by `target/hashdump/CollectionDump.java` from the Java
//! reference runtime).
//!
//! Each case replays an op script against the matching Rust structure (or
//! its Mutable variant for `:transient true`, converted back with
//! `to_persistent`) and asserts the recorded observable state: count,
//! iteration, lookups, rank probes, and RAPID/MURMUR3 hashes.
//!
//! For `:map` and `:set` the corpus pins the Java CHAMP iteration order; the
//! Rust `Map` is a CHAMP port of the Java `Map.java` layout, so exact order
//! is asserted for every case. The entry SET is additionally compared
//! unordered, and count/find/contains/hash are always asserted exactly (a
//! hash mismatch indicates a hashing bug, never a layout difference).

use crate::core::Value;
use crate::kernel::parser::parse_forms;
use crate::kernel::Form;
use crate::lang::data::{
    List, Map, OrderedMap, OrderedSet, Queue, Set, SortedMap, SortedSet, Trie, Vector,
};
use crate::lang::protocol::{HashType, IHash, INth, IToMutable, IToPersistent};

/// Waived assertions as `(case-id, expect-key, reason)` triples. Every entry
/// must reference a live corpus id; stale entries fail the suite. Keep this
/// list honest: only layout/ordering differences belong here, never value,
/// count, lookup, or hash differences. Currently empty: the CHAMP port of
/// `map.rs` matches the Java iteration order for every corpus case.
const SKIP: &[(&str, &str, &str)] = &[];

// ---------------------------------------------------------------------------
// corpus access helpers
// ---------------------------------------------------------------------------

fn corpus_path(relative: &str) -> Option<std::path::PathBuf> {
    crate::spec_registry::resolve(relative).filter(|candidate| candidate.is_file())
}

fn field<'a>(case: &'a Form, key: &str) -> &'a Form {
    match case {
        Form::Map(entries) => entries
            .iter()
            .find(|(k, _)| matches!(k, Form::Keyword(kw) if kw == key))
            .map(|(_, v)| v)
            .unwrap_or_else(|| panic!("case missing :{key}: {case}")),
        other => panic!("case is not a map: {other}"),
    }
}

fn opt_field<'a>(case: &'a Form, key: &str) -> Option<&'a Form> {
    match case {
        Form::Map(entries) => entries
            .iter()
            .find(|(k, _)| matches!(k, Form::Keyword(kw) if kw == key))
            .map(|(_, v)| v),
        other => panic!("case is not a map: {other}"),
    }
}

fn kw_of(form: &Form) -> &str {
    match form {
        Form::Keyword(s) => s,
        other => panic!("expected keyword, got {other}"),
    }
}

fn num_of(form: &Form) -> i64 {
    match form {
        Form::Number(n) => *n,
        other => panic!("expected number, got {other}"),
    }
}

fn bool_of(form: &Form) -> bool {
    match form {
        Form::Bool(b) => *b,
        other => panic!("expected boolean, got {other}"),
    }
}

fn vec_of(form: &Form) -> &Vec<Form> {
    match form {
        Form::Vector(items) => items,
        other => panic!("expected vector, got {other}"),
    }
}

fn map_of(form: &Form) -> &Vec<(Form, Form)> {
    match form {
        Form::Map(entries) => entries,
        other => panic!("expected map, got {other}"),
    }
}

// ---------------------------------------------------------------------------
// value conversion (corpus values are strings and small longs)
// ---------------------------------------------------------------------------

fn arg_value(form: &Form) -> Value {
    match form {
        Form::String(s) => Value::String(s.clone().into()),
        Form::Number(n) => Value::Number(*n),
        other => panic!("unsupported op argument: {other}"),
    }
}

fn value_form(value: &Value) -> Form {
    match value {
        Value::String(s) => Form::String(s.to_string()),
        Value::Number(n) => Form::Number(*n),
        other => panic!("unexpected structure element: {other:?}"),
    }
}

fn opt_value_form(value: Option<&Value>) -> Form {
    value.map(value_form).unwrap_or(Form::Nil)
}

fn op_parts(op: &Form) -> (&str, &[Form]) {
    match op {
        Form::Vector(items) if !items.is_empty() => (kw_of(&items[0]), &items[1..]),
        other => panic!("op must be a non-empty vector: {other}"),
    }
}

// ---------------------------------------------------------------------------
// actual observations
// ---------------------------------------------------------------------------

#[derive(Default)]
struct Actual {
    count: i64,
    iter: Option<Vec<Form>>,
    first: Option<Form>,
    last: Option<Form>,
    hash: i64,
    hash_murmur3: i64,
}

fn hashes<H: IHash>(actual: &mut Actual, structure: &H) {
    actual.hash = structure.hash_calc(HashType::Rapid) as i64;
    actual.hash_murmur3 = structure.hash_calc(HashType::Murmur3) as i64;
}

/// Runs one case and returns failure strings (empty = pass).
fn run_case(case: &Form) -> Vec<String> {
    let id = kw_of(field(case, "id")).to_string();
    let structure = kw_of(field(case, "structure"));
    let transient = bool_of(field(case, "transient"));
    let ops = vec_of(field(case, "ops"));
    let expect = field(case, "expect");

    let mut actual = Actual::default();

    // probe results, keyed the same way as the expect maps
    let mut find_out: Vec<(Form, Form)> = Vec::new();
    let mut contains_out: Vec<(Form, Form)> = Vec::new();
    let mut nth_out: Vec<(Form, Form)> = Vec::new();
    let mut index_of_out: Vec<(Form, Form)> = Vec::new();
    let mut floor_index_out: Vec<(Form, Form)> = Vec::new();
    let mut ceil_index_out: Vec<(Form, Form)> = Vec::new();

    macro_rules! pair_iter {
        ($it:expr) => {
            $it.map(|(k, v)| Form::Vector(vec![value_form(k), value_form(v)]))
                .collect::<Vec<Form>>()
        };
    }

    match structure {
        "map" => {
            let finish = |m: &Map<Value, Value>, actual: &mut Actual| {
                actual.count = m.len() as i64;
                actual.iter = Some(pair_iter!(m.iter()));
                hashes(actual, m);
            };
            if transient {
                let mut m = Map::new().to_mutable();
                for op in ops {
                    let (name, args) = op_parts(op);
                    match name {
                        "assoc" => m.assoc(arg_value(&args[0]), arg_value(&args[1])),
                        "dissoc" => m.dissoc(&arg_value(&args[0])),
                        other => panic!("map op: {other}"),
                    };
                }
                let p = m.to_persistent();
                finish(&p, &mut actual);
                fill_find(&p, expect, &mut find_out);
            } else {
                let mut m = Map::new();
                for op in ops {
                    let (name, args) = op_parts(op);
                    match name {
                        "assoc" => m = m.assoc_value(arg_value(&args[0]), arg_value(&args[1])),
                        "dissoc" => m = m.dissoc_value(&arg_value(&args[0])),
                        other => panic!("map op: {other}"),
                    }
                }
                finish(&m, &mut actual);
                fill_find(&m, expect, &mut find_out);
            }
        }
        "set" => {
            let finish = |s: &Set<Value>, actual: &mut Actual| {
                actual.count = s.len() as i64;
                actual.iter = Some(s.iter().map(value_form).collect());
                hashes(actual, s);
            };
            if transient {
                let mut s = Set::new().to_mutable();
                for op in ops {
                    let (name, args) = op_parts(op);
                    match name {
                        "conj" => s.conj(arg_value(&args[0])),
                        "dissoc" => s.dissoc(&arg_value(&args[0])),
                        other => panic!("set op: {other}"),
                    };
                }
                let p = s.to_persistent();
                finish(&p, &mut actual);
                fill_contains(&p, expect, &mut contains_out);
            } else {
                let mut s = Set::new();
                for op in ops {
                    let (name, args) = op_parts(op);
                    match name {
                        "conj" => s = s.conj_value(arg_value(&args[0])),
                        "dissoc" => s = s.dissoc_value(&arg_value(&args[0])),
                        other => panic!("set op: {other}"),
                    }
                }
                finish(&s, &mut actual);
                fill_contains(&s, expect, &mut contains_out);
            }
        }
        "vector" => {
            let finish = |v: &Vector<Value>, actual: &mut Actual| {
                actual.count = v.len() as i64;
                actual.iter = Some(v.iter().map(value_form).collect());
                hashes(actual, v);
            };
            if transient {
                let mut v = Vector::new().to_mutable();
                for op in ops {
                    let (name, args) = op_parts(op);
                    match name {
                        "push-last" => v.push_last(arg_value(&args[0])),
                        "pop-last" => {
                            v.pop_last();
                            continue;
                        }
                        "assoc" => v.assoc(num_of(&args[0]) as usize, arg_value(&args[1])),
                        other => panic!("vector op: {other}"),
                    };
                }
                let p = v.to_persistent();
                finish(&p, &mut actual);
                fill_nth(&p, expect, &mut nth_out);
            } else {
                let mut v = Vector::new();
                for op in ops {
                    let (name, args) = op_parts(op);
                    match name {
                        "push-last" => v = v.push_last(arg_value(&args[0])),
                        "pop-last" => v = v.pop_last_value().expect("pop-last on empty vector"),
                        "assoc" => {
                            v = v
                                .assoc_value(num_of(&args[0]) as usize, arg_value(&args[1]))
                                .expect("vector assoc index out of range")
                        }
                        other => panic!("vector op: {other}"),
                    }
                }
                finish(&v, &mut actual);
                fill_nth(&v, expect, &mut nth_out);
            }
        }
        "list" => {
            let mut l = List::new();
            for op in ops {
                let (name, args) = op_parts(op);
                match name {
                    "push-first" => l = l.push_first(arg_value(&args[0])),
                    "push-last" => l = l.push_last(arg_value(&args[0])),
                    "pop-first" => l = l.pop_first_value(),
                    "pop-last" => l = l.pop_last_value(),
                    other => panic!("list op: {other}"),
                }
            }
            actual.count = l.len() as i64;
            actual.iter = Some(l.iter().map(value_form).collect());
            hashes(&mut actual, &l);
            fill_nth(&l, expect, &mut nth_out);
        }
        "queue" => {
            let finish = |q: &Queue<Value>, actual: &mut Actual, with_iter: bool| {
                actual.count = q.len() as i64;
                if with_iter {
                    actual.iter = Some(q.iter().map(value_form).collect());
                }
                actual.first = Some(opt_value_form(q.peek_first()));
                actual.last = Some(opt_value_form(q.peek_last()));
                hashes(actual, q);
            };
            let with_iter = opt_field(expect, "iter").is_some();
            if transient {
                let mut q = Queue::new().to_mutable();
                for op in ops {
                    let (name, args) = op_parts(op);
                    match name {
                        "push-last" => q.push_last(arg_value(&args[0])),
                        "pop-first" => q.pop_first(),
                        "pop-last" => q.pop_last(),
                        other => panic!("queue op: {other}"),
                    };
                }
                let p = q.to_persistent();
                finish(&p, &mut actual, with_iter);
                fill_nth(&p, expect, &mut nth_out);
            } else {
                let mut q = Queue::new();
                for op in ops {
                    let (name, args) = op_parts(op);
                    match name {
                        "push-last" => q = q.push_last(arg_value(&args[0])),
                        "pop-first" => q = q.pop_first_value(),
                        "pop-last" => q = q.pop_last_value(),
                        other => panic!("queue op: {other}"),
                    }
                }
                finish(&q, &mut actual, with_iter);
                fill_nth(&q, expect, &mut nth_out);
            }
        }
        "ordered-map" => {
            let finish = |m: &OrderedMap<Value, Value>, actual: &mut Actual| {
                actual.count = m.len() as i64;
                actual.iter = Some(pair_iter!(m.iter()));
                hashes(actual, m);
            };
            if transient {
                let mut m = OrderedMap::new().to_mutable();
                for op in ops {
                    let (name, args) = op_parts(op);
                    match name {
                        "assoc" => m.assoc(arg_value(&args[0]), arg_value(&args[1])),
                        "dissoc" => m.dissoc(&arg_value(&args[0])),
                        other => panic!("ordered-map op: {other}"),
                    };
                }
                let p = m.to_persistent();
                finish(&p, &mut actual);
                fill_find(&p, expect, &mut find_out);
            } else {
                let mut m = OrderedMap::new();
                for op in ops {
                    let (name, args) = op_parts(op);
                    match name {
                        "assoc" => m = m.assoc_value(arg_value(&args[0]), arg_value(&args[1])),
                        "dissoc" => m = m.dissoc_value(&arg_value(&args[0])),
                        other => panic!("ordered-map op: {other}"),
                    }
                }
                finish(&m, &mut actual);
                fill_find(&m, expect, &mut find_out);
            }
        }
        "ordered-set" => {
            let finish = |s: &OrderedSet<Value>, actual: &mut Actual| {
                actual.count = s.len() as i64;
                actual.iter = Some(s.iter().map(value_form).collect());
                hashes(actual, s);
            };
            if transient {
                let mut s = OrderedSet::new().to_mutable();
                for op in ops {
                    let (name, args) = op_parts(op);
                    match name {
                        "conj" => s.conj(arg_value(&args[0])),
                        "dissoc" => s.dissoc(&arg_value(&args[0])),
                        other => panic!("ordered-set op: {other}"),
                    };
                }
                let p = s.to_persistent();
                finish(&p, &mut actual);
                fill_contains(&p, expect, &mut contains_out);
            } else {
                let mut s = OrderedSet::new();
                for op in ops {
                    let (name, args) = op_parts(op);
                    match name {
                        "conj" => s = s.conj_value(arg_value(&args[0])),
                        "dissoc" => s = s.dissoc_value(&arg_value(&args[0])),
                        other => panic!("ordered-set op: {other}"),
                    }
                }
                finish(&s, &mut actual);
                fill_contains(&s, expect, &mut contains_out);
            }
        }
        "sorted-map" => {
            let finish = |m: &SortedMap<Value, Value>, actual: &mut Actual| {
                actual.count = m.len() as i64;
                actual.iter = Some(pair_iter!(m.iter()));
                hashes(actual, m);
            };
            if transient {
                let mut m = SortedMap::new().to_mutable();
                for op in ops {
                    let (name, args) = op_parts(op);
                    match name {
                        "assoc" => m.assoc(arg_value(&args[0]), arg_value(&args[1])),
                        "dissoc" => m.dissoc(&arg_value(&args[0])),
                        other => panic!("sorted-map op: {other}"),
                    };
                }
                let p = m.to_persistent();
                finish(&p, &mut actual);
                fill_find(&p, expect, &mut find_out);
                fill_index_of_sorted_map(&p, expect, &mut index_of_out);
                fill_nth_sorted_map(&p, expect, &mut nth_out);
                fill_floor_ceil_sorted_map(&p, expect, &mut floor_index_out, &mut ceil_index_out);
            } else {
                let mut m = SortedMap::new();
                for op in ops {
                    let (name, args) = op_parts(op);
                    match name {
                        "assoc" => m = m.assoc_value(arg_value(&args[0]), arg_value(&args[1])),
                        "dissoc" => m = m.dissoc_value(&arg_value(&args[0])),
                        other => panic!("sorted-map op: {other}"),
                    }
                }
                finish(&m, &mut actual);
                fill_find(&m, expect, &mut find_out);
                fill_index_of_sorted_map(&m, expect, &mut index_of_out);
                fill_nth_sorted_map(&m, expect, &mut nth_out);
                fill_floor_ceil_sorted_map(&m, expect, &mut floor_index_out, &mut ceil_index_out);
            }
        }
        "sorted-set" => {
            let finish = |s: &SortedSet<Value>, actual: &mut Actual| {
                actual.count = s.len() as i64;
                actual.iter = Some(s.iter().map(value_form).collect());
                hashes(actual, s);
            };
            if transient {
                let mut s = SortedSet::new().to_mutable();
                for op in ops {
                    let (name, args) = op_parts(op);
                    match name {
                        "conj" => s.conj(arg_value(&args[0])),
                        "dissoc" => s.dissoc(&arg_value(&args[0])),
                        other => panic!("sorted-set op: {other}"),
                    };
                }
                let p = s.to_persistent();
                finish(&p, &mut actual);
                fill_contains_sorted_set(&p, expect, &mut contains_out);
                fill_index_of_sorted_set(&p, expect, &mut index_of_out);
                fill_nth_sorted_set(&p, expect, &mut nth_out);
                fill_floor_ceil_sorted_set(&p, expect, &mut floor_index_out, &mut ceil_index_out);
            } else {
                let mut s = SortedSet::new();
                for op in ops {
                    let (name, args) = op_parts(op);
                    match name {
                        "conj" => s = s.conj_value(arg_value(&args[0])),
                        "dissoc" => s = s.dissoc_value(&arg_value(&args[0])),
                        other => panic!("sorted-set op: {other}"),
                    }
                }
                finish(&s, &mut actual);
                fill_contains_sorted_set(&s, expect, &mut contains_out);
                fill_index_of_sorted_set(&s, expect, &mut index_of_out);
                fill_nth_sorted_set(&s, expect, &mut nth_out);
                fill_floor_ceil_sorted_set(&s, expect, &mut floor_index_out, &mut ceil_index_out);
            }
        }
        "trie" => {
            let finish = |t: &Trie<Value>, actual: &mut Actual| {
                actual.count = t.len() as i64;
                actual.iter = Some(
                    t.entries()
                        .iter()
                        .map(|(k, v)| Form::Vector(vec![Form::String(k.clone()), value_form(v)]))
                        .collect(),
                );
                hashes(actual, t);
            };
            if transient {
                let mut t = Trie::new().to_mutable();
                for op in ops {
                    let (name, args) = op_parts(op);
                    match name {
                        "assoc" => t.assoc(str_arg(&args[0]), arg_value(&args[1])),
                        "dissoc" => t.dissoc(&str_arg(&args[0])),
                        other => panic!("trie op: {other}"),
                    };
                }
                let p = t.to_persistent();
                finish(&p, &mut actual);
                fill_trie_find(&p, expect, &mut find_out);
            } else {
                let mut t = Trie::new();
                for op in ops {
                    let (name, args) = op_parts(op);
                    match name {
                        "assoc" => t = t.assoc_value(str_arg(&args[0]), arg_value(&args[1])),
                        "dissoc" => t = t.dissoc_value(&str_arg(&args[0])),
                        other => panic!("trie op: {other}"),
                    }
                }
                finish(&t, &mut actual);
                fill_trie_find(&t, expect, &mut find_out);
            }
        }
        other => panic!("unknown structure: {other}"),
    }

    compare(
        &id,
        structure,
        expect,
        &actual,
        &find_out,
        &contains_out,
        &nth_out,
        &index_of_out,
        &floor_index_out,
        &ceil_index_out,
    )
}

fn str_arg(form: &Form) -> String {
    match form {
        Form::String(s) => s.clone(),
        other => panic!("trie keys must be strings: {other}"),
    }
}

trait Gettable {
    fn get_value(&self, key: &Value) -> Option<&Value>;
}

impl Gettable for Map<Value, Value> {
    fn get_value(&self, key: &Value) -> Option<&Value> {
        self.get(key)
    }
}

impl Gettable for OrderedMap<Value, Value> {
    fn get_value(&self, key: &Value) -> Option<&Value> {
        self.get(key)
    }
}

impl Gettable for SortedMap<Value, Value> {
    fn get_value(&self, key: &Value) -> Option<&Value> {
        self.get(key)
    }
}

fn fill_find<M: Gettable>(m: &M, expect: &Form, out: &mut Vec<(Form, Form)>) {
    if let Some(find) = opt_field(expect, "find") {
        for (probe, _) in map_of(find) {
            out.push((
                probe.clone(),
                opt_value_form(m.get_value(&arg_value(probe))),
            ));
        }
    }
}

trait Containable {
    fn has(&self, value: &Value) -> bool;
}

impl Containable for Set<Value> {
    fn has(&self, value: &Value) -> bool {
        self.contains(value)
    }
}

impl Containable for OrderedSet<Value> {
    fn has(&self, value: &Value) -> bool {
        self.contains(value)
    }
}

fn fill_contains<S: Containable>(s: &S, expect: &Form, out: &mut Vec<(Form, Form)>) {
    if let Some(contains) = opt_field(expect, "contains") {
        for (probe, _) in map_of(contains) {
            out.push((probe.clone(), Form::Bool(s.has(&arg_value(probe)))));
        }
    }
}

fn fill_contains_sorted_set(s: &SortedSet<Value>, expect: &Form, out: &mut Vec<(Form, Form)>) {
    if let Some(contains) = opt_field(expect, "contains") {
        for (probe, _) in map_of(contains) {
            out.push((
                probe.clone(),
                Form::Bool(s.get(&arg_value(probe)).is_some()),
            ));
        }
    }
}

trait Nthable {
    fn nth_value(&self, index: usize) -> Option<&Value>;
}

impl Nthable for Vector<Value> {
    fn nth_value(&self, index: usize) -> Option<&Value> {
        self.get(index)
    }
}

impl Nthable for List<Value> {
    fn nth_value(&self, index: usize) -> Option<&Value> {
        self.get(index)
    }
}

impl Nthable for Queue<Value> {
    fn nth_value(&self, index: usize) -> Option<&Value> {
        self.get(index)
    }
}

fn fill_nth<N: Nthable>(n: &N, expect: &Form, out: &mut Vec<(Form, Form)>) {
    if let Some(nth) = opt_field(expect, "nth") {
        for (idx, _) in map_of(nth) {
            let i = num_of(idx) as usize;
            out.push((idx.clone(), opt_value_form(n.nth_value(i))));
        }
    }
}

fn fill_index_of_sorted_map(
    m: &SortedMap<Value, Value>,
    expect: &Form,
    out: &mut Vec<(Form, Form)>,
) {
    if let Some(index) = opt_field(expect, "index-of") {
        for (probe, _) in map_of(index) {
            let rank = m
                .index_of_key(&arg_value(probe))
                .map(|i| i as i64)
                .unwrap_or(-1);
            out.push((probe.clone(), Form::Number(rank)));
        }
    }
}

fn fill_index_of_sorted_set(s: &SortedSet<Value>, expect: &Form, out: &mut Vec<(Form, Form)>) {
    if let Some(index) = opt_field(expect, "index-of") {
        for (probe, _) in map_of(index) {
            let rank = s
                .index_of(&arg_value(probe))
                .map(|i| i as i64)
                .unwrap_or(-1);
            out.push((probe.clone(), Form::Number(rank)));
        }
    }
}

/// `:nth {idx [k v]}` probes for sorted maps (order-statistic select).
fn fill_nth_sorted_map(m: &SortedMap<Value, Value>, expect: &Form, out: &mut Vec<(Form, Form)>) {
    if let Some(nth) = opt_field(expect, "nth") {
        for (idx, _) in map_of(nth) {
            let i = num_of(idx) as usize;
            out.push((
                idx.clone(),
                m.nth_entry(i)
                    .map(|node| Form::Vector(vec![value_form(&node.key), value_form(&node.value)]))
                    .unwrap_or(Form::Nil),
            ));
        }
    }
}

/// `:nth {idx val}` probes for sorted sets.
fn fill_nth_sorted_set(s: &SortedSet<Value>, expect: &Form, out: &mut Vec<(Form, Form)>) {
    if let Some(nth) = opt_field(expect, "nth") {
        for (idx, _) in map_of(nth) {
            let i = num_of(idx) as usize;
            out.push((idx.clone(), opt_value_form(INth::nth(s, i))));
        }
    }
}

/// `:floor-index`/`:ceil-index` inclusive-rank probes for sorted maps.
fn fill_floor_ceil_sorted_map(
    m: &SortedMap<Value, Value>,
    expect: &Form,
    floor_out: &mut Vec<(Form, Form)>,
    ceil_out: &mut Vec<(Form, Form)>,
) {
    if let Some(floor) = opt_field(expect, "floor-index") {
        for (probe, _) in map_of(floor) {
            let rank = m
                .inclusive_floor_index(&arg_value(probe))
                .map(|i| i as i64)
                .unwrap_or(-1);
            floor_out.push((probe.clone(), Form::Number(rank)));
        }
    }
    if let Some(ceil) = opt_field(expect, "ceil-index") {
        for (probe, _) in map_of(ceil) {
            let rank = m
                .ceil_index(&arg_value(probe))
                .map(|i| i as i64)
                .unwrap_or(-1);
            ceil_out.push((probe.clone(), Form::Number(rank)));
        }
    }
}

/// `:floor-index`/`:ceil-index` inclusive-rank probes for sorted sets.
fn fill_floor_ceil_sorted_set(
    s: &SortedSet<Value>,
    expect: &Form,
    floor_out: &mut Vec<(Form, Form)>,
    ceil_out: &mut Vec<(Form, Form)>,
) {
    if let Some(floor) = opt_field(expect, "floor-index") {
        for (probe, _) in map_of(floor) {
            let rank = s
                .inclusive_floor_index(&arg_value(probe))
                .map(|i| i as i64)
                .unwrap_or(-1);
            floor_out.push((probe.clone(), Form::Number(rank)));
        }
    }
    if let Some(ceil) = opt_field(expect, "ceil-index") {
        for (probe, _) in map_of(ceil) {
            let rank = s
                .ceil_index(&arg_value(probe))
                .map(|i| i as i64)
                .unwrap_or(-1);
            ceil_out.push((probe.clone(), Form::Number(rank)));
        }
    }
}

fn fill_trie_find(t: &Trie<Value>, expect: &Form, out: &mut Vec<(Form, Form)>) {
    if let Some(find) = opt_field(expect, "find") {
        for (probe, _) in map_of(find) {
            out.push((probe.clone(), opt_value_form(t.get(&str_arg(probe)))));
        }
    }
}

// ---------------------------------------------------------------------------
// comparison
// ---------------------------------------------------------------------------

fn skipped(id: &str, key: &str) -> bool {
    SKIP.iter()
        .any(|(skip_id, skip_key, _)| *skip_id == id && *skip_key == key)
}

#[allow(clippy::too_many_arguments)]
fn compare(
    id: &str,
    structure: &str,
    expect: &Form,
    actual: &Actual,
    find_out: &[(Form, Form)],
    contains_out: &[(Form, Form)],
    nth_out: &[(Form, Form)],
    index_of_out: &[(Form, Form)],
    floor_index_out: &[(Form, Form)],
    ceil_index_out: &[(Form, Form)],
) -> Vec<String> {
    let mut failures = Vec::new();
    macro_rules! check {
        ($key:expr, $expected:expr, $rendered_actual:expr) => {
            if !skipped(id, $key) && $expected.to_string() != $rendered_actual {
                failures.push(format!(
                    ":{id} :{}: expected {}, got {}",
                    $key, $expected, $rendered_actual
                ));
            }
        };
    }
    for (key_form, value) in map_of(expect) {
        let key = kw_of(key_form);
        match key {
            "count" => check!(key, value, actual.count.to_string()),
            "hash" => check!(key, value, actual.hash.to_string()),
            "hash-murmur3" => check!(key, value, actual.hash_murmur3.to_string()),
            "iter" => {
                let expected_items = vec_of(value);
                let actual_items = actual.iter.as_ref().expect("iter not recorded");
                if structure == "map" || structure == "set" {
                    // entry-set comparison always; exact CHAMP order unless waived
                    let mut expected_sorted: Vec<String> =
                        expected_items.iter().map(|f| f.to_string()).collect();
                    let mut actual_sorted: Vec<String> =
                        actual_items.iter().map(|f| f.to_string()).collect();
                    expected_sorted.sort();
                    actual_sorted.sort();
                    if expected_sorted != actual_sorted {
                        failures.push(format!(
                            ":{id} :iter (unordered): expected {value}, got {}",
                            Form::Vector(actual_items.clone())
                        ));
                    } else if !skipped(id, "iter-order")
                        && expected_items != actual_items.as_slice()
                    {
                        failures.push(format!(
                            ":{id} :iter-order: expected {value}, got {}",
                            Form::Vector(actual_items.clone())
                        ));
                    }
                } else {
                    check!(key, value, Form::Vector(actual_items.clone()).to_string());
                }
            }
            "first" => check!(
                key,
                value,
                actual
                    .first
                    .clone()
                    .expect("first not recorded")
                    .to_string()
            ),
            "last" => check!(
                key,
                value,
                actual.last.clone().expect("last not recorded").to_string()
            ),
            "find" => check!(key, value, Form::Map(find_out.to_vec()).to_string()),
            "contains" => check!(key, value, Form::Map(contains_out.to_vec()).to_string()),
            "nth" => check!(key, value, Form::Map(nth_out.to_vec()).to_string()),
            "index-of" => check!(key, value, Form::Map(index_of_out.to_vec()).to_string()),
            "floor-index" => check!(key, value, Form::Map(floor_index_out.to_vec()).to_string()),
            "ceil-index" => check!(key, value, Form::Map(ceil_index_out.to_vec()).to_string()),
            other => failures.push(format!(":{id}: unknown expect key :{other}")),
        }
    }
    failures
}

// ---------------------------------------------------------------------------
// test entry point
// ---------------------------------------------------------------------------

#[test]
fn collections_conformance_corpus() {
    let Some(path) = corpus_path("01-lang/020-data-structures/draft/conformance/collections.edn")
    else {
        eprintln!(
            "skipping collections corpus: specs checkout not found from {}",
            env!("HARA_SOURCE_ROOT")
        );
        return;
    };
    let source = std::fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("cannot read {}: {e}", path.display()));
    let forms = parse_forms(&source).expect("collections corpus must parse");
    assert_eq!(forms.len(), 1, "corpus must be a single map form");
    let Form::Vector(cases) = field(&forms[0], "cases") else {
        panic!("corpus :cases must be a vector");
    };

    // stale skip-list detection
    for (skip_id, _, reason) in SKIP {
        assert!(
            cases
                .iter()
                .any(|case| kw_of(field(case, "id")) == *skip_id),
            "skip-list entry :{skip_id} ({reason}) does not match any corpus case"
        );
    }

    let mut failures: Vec<String> = Vec::new();
    for case in cases {
        failures.extend(run_case(case));
    }
    assert!(
        cases.len() >= 40,
        "only {} collections cases found",
        cases.len()
    );
    if !failures.is_empty() {
        panic!(
            "{} collections corpus assertions failed (of {} cases):\n{}",
            failures.len(),
            cases.len(),
            failures.join("\n")
        );
    }
}
