pub(crate) const DIRECT_CALLABLE_CATALOG: &[DirectCallableSpec] = &[
    direct!("%", DirectCallableArity::Exact(2), RuntimePrimitive, Basic),
    direct!("*", DirectCallableArity::Any, RuntimePrimitive, Basic),
    direct!("+", DirectCallableArity::Any, RuntimePrimitive, Basic),
    direct!(
        "-",
        DirectCallableArity::AtLeast(1),
        RuntimePrimitive,
        Basic
    ),
    direct!(
        "/",
        DirectCallableArity::AtLeast(1),
        RuntimePrimitive,
        Basic
    ),
    direct!(
        "<",
        DirectCallableArity::AtLeast(2),
        RuntimePrimitive,
        Basic
    ),
    direct!(
        "<=",
        DirectCallableArity::AtLeast(2),
        RuntimePrimitive,
        Basic
    ),
    direct!(
        "=",
        DirectCallableArity::AtLeast(2),
        RuntimePrimitive,
        Basic
    ),
    direct!(
        ">",
        DirectCallableArity::AtLeast(2),
        RuntimePrimitive,
        Basic
    ),
    direct!(
        ">=",
        DirectCallableArity::AtLeast(2),
        RuntimePrimitive,
        Basic
    ),
    direct!(
        "alter-var-root",
        DirectCallableArity::AtLeast(2),
        RuntimePrimitive,
        AlterVarRoot
    ),
    direct!(
        "any?",
        DirectCallableArity::Between {
            minimum: 1,
            maximum: 2
        },
        BootstrapLibrary,
        Operation(direct_quantifier_operation)
    ),
    direct!(
        "apply",
        DirectCallableArity::AtLeast(2),
        BootstrapLibrary,
        Operation(direct_apply_operation)
    ),
    direct!("array", DirectCallableArity::Any, RuntimePrimitive, Array),
    direct!(
        "assoc",
        DirectCallableArity::OddAtLeast(3),
        RuntimePrimitive,
        Basic
    ),
    direct!(
        "assoc-in",
        DirectCallableArity::Exact(3),
        BootstrapLibrary,
        Operation(direct_nested_collection_operation)
    ),
    direct!(
        "atom",
        DirectCallableArity::Exact(1),
        BootstrapLibrary,
        Operation(direct_reference_operation)
    ),
    direct!(
        "bit-and",
        DirectCallableArity::Exact(2),
        BootstrapLibrary,
        Operation(direct_bit_operation)
    ),
    direct!(
        "bit-not",
        DirectCallableArity::Exact(1),
        BootstrapLibrary,
        Operation(direct_bit_operation)
    ),
    direct!(
        "bit-or",
        DirectCallableArity::Exact(2),
        BootstrapLibrary,
        Operation(direct_bit_operation)
    ),
    direct!(
        "bit-shift-left",
        DirectCallableArity::Exact(2),
        BootstrapLibrary,
        Operation(direct_bit_operation)
    ),
    direct!(
        "bit-shift-right",
        DirectCallableArity::Exact(2),
        BootstrapLibrary,
        Operation(direct_bit_operation)
    ),
    direct!(
        "bit-xor",
        DirectCallableArity::Exact(2),
        BootstrapLibrary,
        Operation(direct_bit_operation)
    ),
    direct!(
        "boolean",
        DirectCallableArity::Exact(1),
        BootstrapLibrary,
        Basic
    ),
    direct!(
        "boolean?",
        DirectCallableArity::Exact(1),
        BootstrapLibrary,
        Operation(direct_predicate_operation)
    ),
    direct!("bytes", DirectCallableArity::Any, RuntimePrimitive, Bytes),
    direct!(
        "capture",
        DirectCallableArity::Exact(1),
        RuntimePrimitive,
        Capture
    ),
    direct!(
        "cas!",
        DirectCallableArity::Exact(3),
        BootstrapLibrary,
        Operation(direct_reference_operation)
    ),
    direct!(
        "char?",
        DirectCallableArity::Exact(1),
        BootstrapLibrary,
        Operation(direct_predicate_operation)
    ),
    direct!(
        "comp",
        DirectCallableArity::AtLeast(2),
        BootstrapLibrary,
        Operation(direct_function_operation)
    ),
    direct!(
        "comp2",
        DirectCallableArity::Exact(2),
        RuntimePrimitive,
        Compose2
    ),
    direct!(
        "comp3",
        DirectCallableArity::Exact(3),
        RuntimePrimitive,
        Compose3
    ),
    direct!(
        "compare",
        DirectCallableArity::Exact(2),
        BootstrapLibrary,
        Basic
    ),
    direct!(
        "complement",
        DirectCallableArity::Exact(1),
        BootstrapLibrary,
        Operation(direct_function_operation)
    ),
    direct!(
        "concat",
        DirectCallableArity::Any,
        BootstrapLibrary,
        Operation(direct_sequence_operation)
    ),
    direct!(
        "conj",
        DirectCallableArity::AtLeast(1),
        RuntimePrimitive,
        Conj
    ),
    direct!(
        "cons",
        DirectCallableArity::Exact(2),
        RuntimePrimitive,
        Cons
    ),
    direct!(
        "constantly",
        DirectCallableArity::Exact(1),
        BootstrapLibrary,
        Operation(direct_function_operation)
    ),
    direct!(
        "count",
        DirectCallableArity::Exact(1),
        RuntimePrimitive,
        Basic
    ),
    direct!(
        "current-namespace",
        DirectCallableArity::Exact(0),
        RuntimePrimitive,
        CurrentNamespace
    ),
    direct!(
        "cycle",
        DirectCallableArity::Exact(1),
        BootstrapLibrary,
        Operation(direct_sequence_operation)
    ),
    direct!(
        "dec",
        DirectCallableArity::Exact(1),
        BootstrapLibrary,
        Operation(direct_numeric_operation)
    ),
    direct!(
        "deref",
        DirectCallableArity::Exact(1),
        RuntimePrimitive,
        Deref
    ),
    direct!(
        "dissoc",
        DirectCallableArity::AtLeast(2),
        RuntimePrimitive,
        Dissoc
    ),
    direct!(
        "double?",
        DirectCallableArity::Exact(1),
        BootstrapLibrary,
        Operation(direct_predicate_operation)
    ),
    direct!(
        "drop",
        DirectCallableArity::Between {
            minimum: 1,
            maximum: 2
        },
        BootstrapLibrary,
        Operation(direct_sequence_operation)
    ),
    direct!(
        "drop-while",
        DirectCallableArity::Between {
            minimum: 1,
            maximum: 2
        },
        BootstrapLibrary,
        Operation(direct_sequence_operation)
    ),
    direct!(
        "empty",
        DirectCallableArity::Exact(1),
        RuntimePrimitive,
        Empty
    ),
    direct!(
        "empty?",
        DirectCallableArity::Exact(1),
        BootstrapLibrary,
        Operation(direct_collection_operation)
    ),
    direct!(
        "eval",
        DirectCallableArity::Exact(1),
        ExplicitSemantic,
        Operation(direct_eval_operation)
    ),
    direct!(
        "eval-in-ns",
        DirectCallableArity::Exact(2),
        ExplicitSemantic,
        Operation(direct_namespace_callable_operation)
    ),
    direct!(
        "even?",
        DirectCallableArity::Exact(1),
        BootstrapLibrary,
        Operation(direct_predicate_operation)
    ),
    direct!(
        "every?",
        DirectCallableArity::Between {
            minimum: 1,
            maximum: 2
        },
        BootstrapLibrary,
        Operation(direct_quantifier_operation)
    ),
    direct!(
        "ex",
        DirectCallableArity::EvenAtLeast(2),
        RuntimePrimitive,
        Exception
    ),
    direct!(
        "ex-cause",
        DirectCallableArity::Exact(1),
        RuntimePrimitive,
        Exception
    ),
    direct!(
        "ex-class",
        DirectCallableArity::Exact(1),
        RuntimePrimitive,
        Exception
    ),
    direct!(
        "ex-data",
        DirectCallableArity::Exact(1),
        RuntimePrimitive,
        Exception
    ),
    direct!(
        "ex-info",
        DirectCallableArity::Between {
            minimum: 2,
            maximum: 3
        },
        RuntimePrimitive,
        Exception
    ),
    direct!(
        "ex-message",
        DirectCallableArity::Exact(1),
        RuntimePrimitive,
        Exception
    ),
    direct!(
        "ex-native-type",
        DirectCallableArity::Exact(1),
        RuntimePrimitive,
        Exception
    ),
    direct!(
        "ex-provenance",
        DirectCallableArity::Exact(1),
        RuntimePrimitive,
        Exception
    ),
    direct!(
        "false?",
        DirectCallableArity::Exact(1),
        BootstrapLibrary,
        Operation(direct_predicate_operation)
    ),
    direct!(
        "filter",
        DirectCallableArity::Between {
            minimum: 1,
            maximum: 2
        },
        BootstrapLibrary,
        Operation(direct_sequence_operation)
    ),
    direct!(
        "first",
        DirectCallableArity::Exact(1),
        BootstrapLibrary,
        Operation(direct_collection_operation)
    ),
    direct!(
        "fn?",
        DirectCallableArity::Exact(1),
        BootstrapLibrary,
        Operation(direct_predicate_operation)
    ),
    direct!(
        "function?",
        DirectCallableArity::Exact(1),
        BootstrapLibrary,
        Operation(direct_predicate_operation)
    ),
    direct!(
        "get",
        DirectCallableArity::Between {
            minimum: 2,
            maximum: 3
        },
        RuntimePrimitive,
        Basic
    ),
    direct!(
        "get-in",
        DirectCallableArity::Exact(2),
        BootstrapLibrary,
        Operation(direct_nested_collection_operation)
    ),
    direct!(
        "hash-map",
        DirectCallableArity::Even,
        BootstrapLibrary,
        Operation(direct_constructor_operation)
    ),
    direct!(
        "hash-set",
        DirectCallableArity::Any,
        BootstrapLibrary,
        Operation(direct_constructor_operation)
    ),
    direct!(
        "identity",
        DirectCallableArity::Exact(1),
        BootstrapLibrary,
        Operation(direct_function_operation)
    ),
    direct!(
        "inc",
        DirectCallableArity::Exact(1),
        BootstrapLibrary,
        Operation(direct_numeric_operation)
    ),
    direct!(
        "instance?",
        DirectCallableArity::Exact(2),
        BootstrapLibrary,
        Operation(direct_predicate_operation)
    ),
    direct!(
        "integer?",
        DirectCallableArity::Exact(1),
        BootstrapLibrary,
        Basic
    ),
    direct!(
        "interleave",
        DirectCallableArity::AtLeast(1),
        BootstrapLibrary,
        Operation(direct_sequence_operation)
    ),
    direct!(
        "intern-var",
        DirectCallableArity::Between {
            minimum: 3,
            maximum: 4
        },
        NamespaceMutation,
        Operation(direct_namespace_callable_operation)
    ),
    direct!(
        "interpose",
        DirectCallableArity::Between {
            minimum: 1,
            maximum: 2
        },
        BootstrapLibrary,
        Operation(direct_sequence_operation)
    ),
    direct!(
        "iter",
        DirectCallableArity::Exact(1),
        RuntimePrimitive,
        Iter
    ),
    direct!(
        "iter-next",
        DirectCallableArity::Exact(1),
        RuntimePrimitive,
        IterNext
    ),
    direct!(
        "iter-next?",
        DirectCallableArity::Exact(1),
        RuntimePrimitive,
        IterNextPredicate
    ),
    direct!(
        "iter?",
        DirectCallableArity::Exact(1),
        RuntimePrimitive,
        IterPredicate
    ),
    direct!(
        "iterate",
        DirectCallableArity::Exact(2),
        BootstrapLibrary,
        Operation(direct_sequence_operation)
    ),
    direct!(
        "keep",
        DirectCallableArity::Between {
            minimum: 1,
            maximum: 2
        },
        BootstrapLibrary,
        Operation(direct_sequence_operation)
    ),
    direct!(
        "key",
        DirectCallableArity::Exact(1),
        BootstrapLibrary,
        Operation(direct_collection_operation)
    ),
    direct!(
        "keys",
        DirectCallableArity::Exact(1),
        BootstrapLibrary,
        Operation(direct_collection_operation)
    ),
    direct!(
        "keyword",
        DirectCallableArity::Between {
            minimum: 1,
            maximum: 2
        },
        BootstrapLibrary,
        Operation(direct_constructor_operation)
    ),
    direct!(
        "keyword?",
        DirectCallableArity::Exact(1),
        BootstrapLibrary,
        Operation(direct_predicate_operation)
    ),
    direct!(
        "last",
        DirectCallableArity::Exact(1),
        BootstrapLibrary,
        Operation(direct_collection_operation)
    ),
    direct!("list", DirectCallableArity::Any, BootstrapLibrary, List),
    direct!(
        "list?",
        DirectCallableArity::Exact(1),
        BootstrapLibrary,
        Operation(direct_predicate_operation)
    ),
    direct!(
        "load-string",
        DirectCallableArity::Exact(1),
        ExplicitSemantic,
        LoadString
    ),
    direct!(
        "long?",
        DirectCallableArity::Exact(1),
        BootstrapLibrary,
        Operation(direct_predicate_operation)
    ),
    direct!(
        "map",
        DirectCallableArity::AtLeast(1),
        BootstrapLibrary,
        Operation(direct_sequence_operation)
    ),
    direct!(
        "map?",
        DirectCallableArity::Exact(1),
        BootstrapLibrary,
        Operation(direct_predicate_operation)
    ),
    direct!(
        "mapcat",
        DirectCallableArity::Between {
            minimum: 1,
            maximum: 2
        },
        BootstrapLibrary,
        Operation(direct_sequence_operation)
    ),
    direct!(
        "meta",
        DirectCallableArity::Exact(1),
        BootstrapLibrary,
        Basic
    ),
    direct!(
        "mod",
        DirectCallableArity::Exact(2),
        RuntimePrimitive,
        Basic
    ),
    direct!(
        "name",
        DirectCallableArity::Exact(1),
        RuntimePrimitive,
        Name
    ),
    direct!(
        "namespace",
        DirectCallableArity::Exact(1),
        RuntimePrimitive,
        Namespace
    ),
    direct!(
        "neg?",
        DirectCallableArity::Exact(1),
        BootstrapLibrary,
        Operation(direct_predicate_operation)
    ),
    direct!(
        "nil?",
        DirectCallableArity::Exact(1),
        BootstrapLibrary,
        Operation(direct_predicate_operation)
    ),
    direct!(
        "not",
        DirectCallableArity::Exact(1),
        BootstrapLibrary,
        Operation(direct_function_operation)
    ),
    direct!(
        "not-empty",
        DirectCallableArity::Exact(1),
        BootstrapLibrary,
        Operation(direct_collection_operation)
    ),
    direct!(
        "not=",
        DirectCallableArity::AtLeast(2),
        RuntimePrimitive,
        Basic
    ),
    direct!(
        "ns-alias-state",
        DirectCallableArity::Between {
            minimum: 1,
            maximum: 2
        },
        BootstrapLibrary,
        Operation(direct_namespace_callable_operation)
    ),
    direct!(
        "ns-loaded?",
        DirectCallableArity::Exact(1),
        RuntimePrimitive,
        NamespaceLoaded
    ),
    direct!(
        "ns-state",
        DirectCallableArity::Exact(1),
        RuntimePrimitive,
        NamespaceState
    ),
    direct!(
        "ns:create",
        DirectCallableArity::Exact(1),
        NamespaceMutation,
        NamespaceCreate
    ),
    direct!(
        "nth",
        DirectCallableArity::Exact(2),
        RuntimePrimitive,
        Basic
    ),
    direct!(
        "number?",
        DirectCallableArity::Exact(1),
        BootstrapLibrary,
        Operation(direct_predicate_operation)
    ),
    direct!(
        "object",
        DirectCallableArity::Even,
        RuntimePrimitive,
        Object
    ),
    direct!(
        "odd?",
        DirectCallableArity::Exact(1),
        BootstrapLibrary,
        Operation(direct_predicate_operation)
    ),
    direct!("p", DirectCallableArity::Any, RuntimePrimitive, Print),
    direct!(
        "pair",
        DirectCallableArity::Exact(2),
        BootstrapLibrary,
        Operation(direct_constructor_operation)
    ),
    direct!(
        "partition",
        DirectCallableArity::Between {
            minimum: 1,
            maximum: 2
        },
        BootstrapLibrary,
        Operation(direct_sequence_operation)
    ),
    direct!(
        "partition-all",
        DirectCallableArity::Between {
            minimum: 1,
            maximum: 2
        },
        BootstrapLibrary,
        Operation(direct_sequence_operation)
    ),
    direct!(
        "partition-pair",
        DirectCallableArity::Exact(1),
        BootstrapLibrary,
        Operation(direct_sequence_operation)
    ),
    direct!(
        "peek",
        DirectCallableArity::Exact(1),
        RuntimePrimitive,
        Peek
    ),
    direct!(
        "pointer",
        DirectCallableArity::Exact(1),
        BootstrapLibrary,
        Operation(direct_constructor_operation)
    ),
    direct!(
        "pos?",
        DirectCallableArity::Exact(1),
        BootstrapLibrary,
        Operation(direct_predicate_operation)
    ),
    direct!(
        "pr-str",
        DirectCallableArity::Exact(1),
        RuntimePrimitive,
        PrintRepresentation
    ),
    direct!(
        "println",
        DirectCallableArity::Any,
        RuntimePrimitive,
        Println
    ),
    direct!(
        "promise",
        DirectCallableArity::Exact(1),
        RuntimePrimitive,
        Promise
    ),
    direct!(
        "promise/delay",
        DirectCallableArity::Exact(2),
        RuntimePrimitive,
        Operation(direct_promise_operation)
    ),
    direct!(
        "promise/new",
        DirectCallableArity::Exact(1),
        RuntimePrimitive,
        Operation(direct_promise_operation)
    ),
    direct!(
        "promise?",
        DirectCallableArity::Exact(1),
        RuntimePrimitive,
        PromisePredicate
    ),
    direct!(
        "quot",
        DirectCallableArity::Exact(2),
        RuntimePrimitive,
        Basic
    ),
    direct!(
        "range",
        DirectCallableArity::Between {
            minimum: 0,
            maximum: 2
        },
        BootstrapLibrary,
        Operation(direct_sequence_operation)
    ),
    direct!(
        "read-string",
        DirectCallableArity::Exact(1),
        RuntimePrimitive,
        ReadString
    ),
    direct!(
        "rem",
        DirectCallableArity::Exact(2),
        RuntimePrimitive,
        Basic
    ),
    direct!(
        "repeat",
        DirectCallableArity::Between {
            minimum: 1,
            maximum: 2
        },
        BootstrapLibrary,
        Operation(direct_sequence_operation)
    ),
    direct!(
        "repeatedly",
        DirectCallableArity::Between {
            minimum: 1,
            maximum: 2
        },
        BootstrapLibrary,
        Operation(direct_sequence_operation)
    ),
    direct!(
        "reset!",
        DirectCallableArity::Exact(2),
        BootstrapLibrary,
        Operation(direct_reference_operation)
    ),
    direct!(
        "resolve",
        DirectCallableArity::Exact(1),
        RuntimePrimitive,
        Resolve
    ),
    direct!(
        "rest",
        DirectCallableArity::Exact(1),
        BootstrapLibrary,
        Operation(direct_collection_operation)
    ),
    direct!(
        "reverse",
        DirectCallableArity::Exact(1),
        BootstrapLibrary,
        Operation(direct_collection_operation)
    ),
    direct!(
        "second",
        DirectCallableArity::Exact(1),
        BootstrapLibrary,
        Operation(direct_collection_operation)
    ),
    direct!(
        "seq",
        DirectCallableArity::Between {
            minimum: 1,
            maximum: 2
        },
        RuntimePrimitive,
        Seq
    ),
    direct!(
        "seq?",
        DirectCallableArity::Exact(1),
        RuntimePrimitive,
        SeqPredicate
    ),
    direct!(
        "set?",
        DirectCallableArity::Exact(1),
        BootstrapLibrary,
        Operation(direct_predicate_operation)
    ),
    direct!(
        "satisfies?",
        DirectCallableArity::Exact(2),
        BootstrapLibrary,
        Operation(direct_predicate_operation)
    ),
    direct!("str", DirectCallableArity::Any, RuntimePrimitive, String),
    direct!(
        "string?",
        DirectCallableArity::Exact(1),
        BootstrapLibrary,
        Operation(direct_predicate_operation)
    ),
    direct!(
        "swap!",
        DirectCallableArity::AtLeast(2),
        BootstrapLibrary,
        Operation(direct_reference_operation)
    ),
    direct!(
        "symbol",
        DirectCallableArity::Between {
            minimum: 1,
            maximum: 2
        },
        BootstrapLibrary,
        Operation(direct_constructor_operation)
    ),
    direct!(
        "symbol?",
        DirectCallableArity::Exact(1),
        BootstrapLibrary,
        Operation(direct_predicate_operation)
    ),
    direct!(
        "take",
        DirectCallableArity::Between {
            minimum: 1,
            maximum: 2
        },
        BootstrapLibrary,
        Operation(direct_sequence_operation)
    ),
    direct!(
        "take-while",
        DirectCallableArity::Between {
            minimum: 1,
            maximum: 2
        },
        BootstrapLibrary,
        Operation(direct_sequence_operation)
    ),
    direct!(
        "true?",
        DirectCallableArity::Exact(1),
        BootstrapLibrary,
        Operation(direct_predicate_operation)
    ),
    direct!(
        "tup",
        DirectCallableArity::Between {
            minimum: 0,
            maximum: 5
        },
        RuntimePrimitive,
        Tuple
    ),
    direct!(
        "type",
        DirectCallableArity::Exact(1),
        BootstrapLibrary,
        Type
    ),
    direct!(
        "update",
        DirectCallableArity::AtLeast(3),
        BootstrapLibrary,
        Operation(direct_nested_collection_operation)
    ),
    direct!(
        "update-in",
        DirectCallableArity::AtLeast(3),
        BootstrapLibrary,
        Operation(direct_nested_collection_operation)
    ),
    direct!(
        "val",
        DirectCallableArity::Exact(1),
        BootstrapLibrary,
        Operation(direct_collection_operation)
    ),
    direct!(
        "vals",
        DirectCallableArity::Exact(1),
        BootstrapLibrary,
        Operation(direct_collection_operation)
    ),
    direct!(
        "var-sym",
        DirectCallableArity::Exact(1),
        BootstrapLibrary,
        Operation(direct_namespace_callable_operation)
    ),
    direct!(
        "vector",
        DirectCallableArity::Any,
        BootstrapLibrary,
        Operation(direct_constructor_operation)
    ),
    direct!(
        "vector?",
        DirectCallableArity::Exact(1),
        BootstrapLibrary,
        Operation(direct_predicate_operation)
    ),
    direct!(
        "with-meta",
        DirectCallableArity::Exact(2),
        BootstrapLibrary,
        WithMeta
    ),
    direct!(
        "zero?",
        DirectCallableArity::Exact(1),
        BootstrapLibrary,
        Operation(direct_predicate_operation)
    ),
    direct!(
        "zip",
        DirectCallableArity::AtLeast(2),
        BootstrapLibrary,
        Operation(direct_sequence_operation)
    ),
];
