import { decodeHta, encodeHta, HtaKeyword, HTA_MAX_FRAME_BYTES } from "./index.js";

let instance,abiVersion; const requests=new Map(); const tasks=new Map(); const hostTasks=new Map(); const externrefTable=[];
const wasmImports={env:{hara_random_fill(pointer,length){const memory=instance?.exports.memory;if(!memory)throw new Error("hta/memory-unavailable");crypto.getRandomValues(new Uint8Array(memory.buffer,pointer,length));return 0;},hara_time_ms(){return BigInt(Math.trunc(Date.now()));},hara_time_ns(){return BigInt(Math.trunc(performance.now()*1_000_000));}},"__wbindgen_placeholder__":{__wbindgen_describe(){},__wbg___wbindgen_throw_bb96b2010945f0bc(pointer,length){const bytes=instance?new Uint8Array(instance.exports.memory.buffer,pointer,length):[];throw new Error(instance?new TextDecoder().decode(bytes):"wasm error");}},"__wbindgen_externref_xform__":{__wbindgen_externref_table_grow(size){const previous=externrefTable.length;externrefTable.length+=size;return previous;},__wbindgen_externref_table_set_null(index){externrefTable[index]=undefined;}}};
self.addEventListener("message", async event=>{try{const message=event.data;if(message.type==="init"){const bytes=message.moduleBytes??await(await fetch(message.moduleUrl)).arrayBuffer();const libraryBytes=message.libraryBytes??(message.libraryUrl?await(await fetch(message.libraryUrl)).arrayBuffer():null);const imports={...wasmImports};if(libraryBytes){const library=(await WebAssembly.instantiate(libraryBytes,imports)).instance;imports["hara/library"]={};for(const entry of WebAssembly.Module.imports(await WebAssembly.compile(bytes)))if(entry.module==="hara/library"){const exported=library.exports[entry.name];if(exported===undefined)throw new Error(`hta/library-export-missing: ${entry.name}`);imports["hara/library"][entry.name]=exported;}}instance=(await WebAssembly.instantiate(bytes,imports)).instance;required();self.postMessage({type:"ready"});}
else if(message.type==="call"){const session=requestSession(message.frame),task=Number(callFrame(instance.exports.hta_start,message.frame));if(task<=0)throw new Error("hta/start-failed");requests.set(message.id,task);tasks.set(task,{id:message.id,session});pump();}
else if(message.type==="delivery"){const task=hostTasks.get(message.call);if(task===undefined||!tasks.has(task)){hostTasks.delete(message.call);pump();return;}hostTasks.delete(message.call);callFrame(instance.exports.hta_deliver,encodeHta([message.call,message.ok?0:1,decodeHta(message.frame)]));pump();}
else if(message.type==="cancel"){const task=requests.get(message.id);if(task!==undefined){const cancelStatus=instance.exports.hta_cancel(BigInt(task));const dropStatus=instance.exports.hta_drop_task(BigInt(task));requests.delete(message.id);tasks.delete(task);removeHostTasks(task);if(cancelStatus!==0)throw new Error(`hta/cancel-failed: ${cancelStatus}`);if(dropStatus!==0)throw new Error(`hta/drop-task-failed: ${dropStatus}`);pump();}}
else if(message.type==="release"){callFrame(instance.exports.hta_release,message.frame);pump();}
else if(message.type==="close")self.close();}catch(error){self.postMessage({type:"fatal",error:{message:String(error?.message??error)}});}});

function required(){for(const name of["memory","hta_abi_version","hta_alloc","hta_dealloc","hta_start","hta_next_event","hta_deliver","hta_cancel","hta_drop_task","hta_release"])if(!(name in instance.exports))throw new Error(`hta/export-missing: ${name}`);abiVersion=instance.exports.hta_abi_version();if(abiVersion!==1&&abiVersion!==2&&abiVersion!==3&&abiVersion!==4)throw new Error("hta/version-unsupported");}
function callFrame(fn,frame){const bytes=frame instanceof Uint8Array?frame:new Uint8Array(frame);if(bytes.length>HTA_MAX_FRAME_BYTES)throw new Error("hta/value-too-large: frame exceeds 64 MiB");const pointer=Number(instance.exports.hta_alloc(bytes.length));new Uint8Array(instance.exports.memory.buffer,pointer,bytes.length).set(bytes);try{return fn(pointer,bytes.length);}finally{instance.exports.hta_dealloc(pointer,bytes.length);}}
function next(){const packed=instance.exports.hta_next_event();if(packed===0n)return null;const pointer=Number(packed>>32n),size=Number(packed&0xffff_ffffn);if(size>HTA_MAX_FRAME_BYTES){instance.exports.hta_dealloc(pointer,size);throw new Error("hta/value-too-large: frame exceeds 64 MiB");}const frame=new Uint8Array(instance.exports.memory.buffer,pointer,size).slice();instance.exports.hta_dealloc(pointer,size);return decodeHta(frame);}
function requestSession(frame){const [target,args]=decodeHta(frame);return typeof target==="string"&&target.startsWith("session/")&&["session/eval","session/eval-vm","session/eval-bound","session/trace-eval"].includes(target)&&typeof args?.[0]==="string"?args[0]:"ROOT";}
function pump(){for(let event;(event=next())!==null;){const kind=Number(event[0]);if(kind===0||kind===1){const task=Number(event[1]),request=tasks.get(task);if(!request)continue;tasks.delete(task);requests.delete(request.id);removeHostTasks(task);instance.exports.hta_drop_task(BigInt(task));self.postMessage({type:"result",id:request.id,ok:kind===0,frame:encodeHta(event[2])});}else if(kind===2){const call=Number(event[1]),task=Number(event[2]);hostTasks.set(call,task);if(abiVersion>=2)self.postMessage({type:"host-call",call,task,session:event[3],mount:event[4]??null,service:event[5],method:event[6],frame:encodeHta(event[7])});else{const request=tasks.get(task);self.postMessage({type:"host-call",call,task,session:request?.session??"ROOT",mount:null,service:event[3],method:event[4],frame:encodeHta(event[5])});}}else throw new Error(`hta/event-unknown: ${kind}`);}}
function removeHostTasks(task){for(const [call,pendingTask] of hostTasks)if(pendingTask===task)hostTasks.delete(call);}
